### ISSUE TITLE
Possible bug (or is the indentation off?)

### ISSUE THREAD

**Issue by jonakarl** [MONROE-PROJECT/Scheduler#12]
https://github.com/MONROE-PROJECT/Scheduler/blob/be0468e312223ef686c89d4a9b2816ed2b075daa/files/usr/bin/container-stop.sh#L132

I cannot find the matching if for this fi

**Comment by relet** [comment]
probably a bug. Fortunately, container-stop isn't on set -e, so it won't break

**Comment by jonakarl** [comment]
Could leave possibly leave dangling files.

--
Jonas Karlsson
Senior Research Engineer
Karlstad University
SE-651 88 Karlstad, Sweden
Telephone: +46 54 700 15 64
Mobile: +46 70 672 06 20
Skype: karlsson.karl.jonas
PGP/GPG : 0x88765911B284F3A6

twitter.com/kau
facebook.com/karlstadsuniversitet
KAU.SE

On 16 Mar 2018, 15:22 +0100, Thomas Hirsch <notifications@github.com>, wrote:

probably a bug. Fortunately, container-stop isn't on set -e, so it won't break
