### ISSUE TITLE
Delete REST function does not delete some experiments.

### ISSUE THREAD

**Issue by mikepeon** [MONROE-PROJECT/Scheduler#2]
For a finished experiment,
DELETE https://scheduler.monroe-system.eu:443/v1/experiments/8
returns:
{
    "aborted": 0,
    "canceled": 0,
    "message": "Ok. Canceled or aborted scheduling entries"
}
The message on marvin's screen is OK:
127.0.0.1:48768 - - [08/Nov/2016 18:23:33] "HTTP/1.1 DELETE /v1/experiments/8" - 200 OK

However, the experiment does not disappear and can be retrieved with 
GET https://scheduler.monroe-system.eu:443/v1/experiments/8

**Comment by relet** [comment]
The DELETE call only
- deletes an experiment if all entries are set to 'defined'.
- otherwise sets the scheduling entries to aborted if they are not in a
  final state.
- does not touch final states (finished, stopped, failed, etc.)

**Comment by relet** [comment]
This is as designed. The function is meant to abort an experiment before it is run, not remove traces of finished experiments.
